apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata: 
  name: hello-policy
spec:
  runAsUser:
    rule: 'MustRunAsNonRoot'
  allowPrivilegeEscalation: false
  seLinux:
    rule: 'MustRunAs'
  fsGroup:
    rule: 'MustRunAs'
    ranges:
      - min: 1
        max: 65535
  readOnlyRootFilesystem: false
  supplementalGroups:
    rule: 'MustRunAs'
    ranges:
      - min: 1
        max: 65535
